# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: Sample


pool:
  vmImage: ubuntu-latest

steps:
- script: echo Varibles is $(DynamicVar)
  displayName: 'Variable display'

- script: |
    newValue="15"
    echo $SYSTEM_ACCESSTOKEN | az devops login
    az pipelines variable-group variable update --group-id 2 \
      --name DynamicVar \
      --value "${newValue}" \
      --org https://dev.azure.com/eduardsocea94 \
      --project MultiBuild-PipelineTest
  displayName: 'Update variable inside a variable group'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

# - script: 
# - bash: echo "##vso[task.setvariable variable=DynamicVar]15"
#   displayName: Set new variable value

- script: echo Varibles is $(DynamicVar)
  displayName: 'Variable display'
