# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: Sample

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Varibles is $(DynamicVar)
  displayName: 'Variable display'

- bash: echo "##vso[task.setvariable variable=DynamicVar]15"
  displayName: Set new variable value

- script: echo Varibles is $(DynamicVar)
  displayName: 'Variable display'
